// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTUkGb-ZGaWCUKg8JJQKAAoTrilNgCzpE',
    appId: '1:304603266106:web:dad113efe41bce204bc903',
    messagingSenderId: '304603266106',
    projectId: 'todoapp-3d4c6',
    authDomain: 'todoapp-3d4c6.firebaseapp.com',
    storageBucket: 'todoapp-3d4c6.firebasestorage.app',
    measurementId: 'G-VRPXETD28W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMg1_dC_UsQHf8XdKNG_ye7b-9PlsT2PE',
    appId: '1:304603266106:android:1d459a11a73673914bc903',
    messagingSenderId: '304603266106',
    projectId: 'todoapp-3d4c6',
    storageBucket: 'todoapp-3d4c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFPbjA9LoPH2O5I5vGHHVum4C6FA0CgTM',
    appId: '1:304603266106:ios:b29f012c6de56f744bc903',
    messagingSenderId: '304603266106',
    projectId: 'todoapp-3d4c6',
    storageBucket: 'todoapp-3d4c6.firebasestorage.app',
    iosBundleId: 'com.example.todoRappid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFPbjA9LoPH2O5I5vGHHVum4C6FA0CgTM',
    appId: '1:304603266106:ios:b29f012c6de56f744bc903',
    messagingSenderId: '304603266106',
    projectId: 'todoapp-3d4c6',
    storageBucket: 'todoapp-3d4c6.firebasestorage.app',
    iosBundleId: 'com.example.todoRappid',
  );

}